name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "export HIDDEN_TOKEN=${{ secrets.TMDB_TOKEN }}" >> $GITHUB_ENV

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies and build for production
      run: |
        npm install
        sed -e "s/HIDDEN_TOKEN/$HIDDEN_TOKEN/g" src/environments/environment.prod.ts.template > src/environments/environment.ts
        sed -e "s/HIDDEN_TOKEN/$HIDDEN_TOKEN/g" src/environments/environment.prod.ts.template > src/environments/environment.prod.ts
        ng b --configuration production

    - name: Copy files to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/cineba/*"
        target: "~/cineba-api/wwwroot"
