name: Debug SSH Connection

on:
  push:
    branches:
      - dev

jobs:
  debug-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Debug SSH Connection
      run: |
        echo "Host: ${{ secrets.HOST }}"
        echo "Username: ${{ secrets.USERNAME }}"
        echo "SSH Key: ${{ secrets.SSH_KEY }}"
        nc -zv ${{ secrets.HOST }} 22
        ssh -v -i ${{ secrets.SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p 22 "echo Hello from the remote server"
