name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "export HIDDEN_TOKEN=${{ secrets.TMDB_TOKEN }}" >> $GITHUB_ENV

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies and build for production
      run: |
        npm install
        sed -e "s/HIDDEN_TOKEN/$HIDDEN_TOKEN/g" src/environments/environment.prod.ts.template > src/environments/environment.ts
        sed -e "s/HIDDEN_TOKEN/$HIDDEN_TOKEN/g" src/environments/environment.prod.ts.template > src/environments/environment.prod.ts
        ng b --configuration production

    - name: Debug
      run: |
        ls -R $GITHUB_WORKSPACE/dist/cineba

    - name: Create a version file with the commit hash and tag
      run: |
        echo $GITHUB_SHA > dist/cineba/version.txt
        echo $GITHUB_REF >> dist/cineba/version.txt

    - name: Copy files to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/bitnami/cineba-api/wwwroot
          scp -r $GITHUB_WORKSPACE/dist/cineba/* .
          pm2 restart serve
