name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  check-keys:
    runs-on: ubuntu-latest

    steps:
    - name: Check if SSH keys exist
      run: |
        if [ -z "${{ secrets.HOST }}" ]; then
          echo "Error: HOST is missing in GitHub Secrets."
          exit 1
        fi

        if [ -z "${{ secrets.USERNAME }}" ]; then
          echo "Error: USERNAME is missing in GitHub Secrets."
          exit 1
        fi

        if [ -z "${{ secrets.SSH_KEY }}" ]; then
          echo "Error: SSH_KEY is missing in GitHub Secrets."
          exit 1
        fi

  deploy:
    needs: check-keys
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "export HIDDEN_TOKEN=${{ secrets.TMDB_TOKEN }}" >> $GITHUB_ENV

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies and build for production
      run: |
        npm install
        sed -e "s/HIDDEN_TOKEN/$HIDDEN_TOKEN/g" src/environments/environment.prod.ts.template > src/environments/environment.ts
        sed -e "s/HIDDEN_TOKEN/$HIDDEN_TOKEN/g" src/environments/environment.prod.ts.template > src/environments/environment.prod.ts
        ng b --configuration production

    - name: Create a version file with the commit hash and tag
      run: |
        echo $GITHUB_SHA > dist/cineba/version.txt
        echo $GITHUB_REF >> dist/cineba/version.txt

    - name: Copy files to server using scp
      run: |
        scp -r -i ${{ secrets.SSH_KEY }} dist/cineba/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/cineba-api/wwwroot
